# Generated by Django 3.0.1 on 2019-12-22 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settore',
            name='descrizione',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
