# Generated by Django 3.0.1 on 2019-12-21 21:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='descrizione',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
