# Generated by Django 3.0.1 on 2019-12-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lavoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committente', models.CharField(max_length=250)),
                ('titolo', models.CharField(max_length=250)),
                ('anno', models.IntegerField()),
            ],
        ),
    ]
